In [2]:
import numpy as np

# 1 - NumPy Data Structures

## Arrays

* Arrays are the fundamental Data Structure provided by NumPy
* Arrays are similar to lists in Python
* But every element of an array must be of the same type (for example, float or int)
    - Vectorization
    - Write vectorized code with functional programming paradigm
* Arrays make operations with large amounts of numeric data very fast and efficient

### Creating Arrays from Python Lists

In [2]:
a = np.array([1, 4, 5, 8], float)
a

array([ 1.,  4.,  5.,  8.])

In [4]:
type(a)

numpy.ndarray

In [75]:
a.dtype

dtype('float64')

### Creating Arrays with *arange()*

The *arange* function is similar to the *range* function but returns an array

In [76]:
x = np.arange(5, dtype=float)
y = np.arange(1, 6, 2, dtype=int)

x

array([ 0.,  1.,  2.,  3.,  4.])

In [77]:
y

array([1, 3, 5])

In [78]:
type(x)

numpy.ndarray

In [81]:
y.dtype

dtype('int64')

### Creating Arrays with *zeroes* and *ones*

In [82]:
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [83]:
np.ones((2,3), dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [84]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
np.zeros_like(a)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [86]:
np.ones_like(a)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### Creating Special Arrays

In [87]:
 np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

The *eye* function returns matrices with ones along the kth diagonal

In [4]:
np.eye(4, k=1, dtype=float)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

### Array Subsetting

Note: Array subsetting (and manipulation) is similar to how we subset (manipulate) Lists

In [11]:
a[:2]

array([ 5.,  4.])

In [12]:
a[3]

8.0

In [13]:
a[0] = 5.
a

array([ 5.,  4.,  5.,  8.])

### Multi-dimensional Arrays

* Arrays can be multidimensional.
* Unlike lists, different axes are accessed using commas inside bracket notation. 

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [17]:
a[0,0]

1.0

In [24]:
a[0,1]

2.0

### Multi-dimensional Array Subsetting

* Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension
* Use of a single ":" in a dimension indicates the use of everything along that dimension

In [25]:
a[:,0]

array([ 1.,  4.])

In [29]:
a[1,:]

array([ 4.,  5.,  6.])

Note: The subsetting behaviour here is different from how it works in R

In [27]:
a[1,:].dtype

dtype('float64')

In [31]:
type(a[1,:])

numpy.ndarray

Class exercise: Explain the output below:

In [30]:
a[-1:,-2:]

array([[ 5.,  6.]])

## The Shape of an Array

The shape property of an array returns a tuple with the size of each array dimension

In [33]:
a.shape

(2, 3)

* Arrays can be reshaped using tuples that specify new dimensions.
* In the following example, we turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements

In [38]:
b = np.array(range(10), float)
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [39]:
b = b.reshape((5, 2))
b

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

Notice that the reshape function creates a new array and does not itself modify the original array

In [41]:
b.reshape((2, 5))

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [68]:
b.shape

(2, 2)

The dimensionality of an array can be increased using the newaxis constant in bracket notation

In [69]:
a = np.array([1, 2, 3], float)
a

array([ 1.,  2.,  3.])

In [70]:
a[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.]])

In [71]:
a[:,np.newaxis].shape

(3, 1)

In [72]:
b[np.newaxis,:]

array([[[ 5.,  6.],
        [ 7.,  8.]]])

In [74]:
b[np.newaxis,:].shape

(1, 2, 2)

The dimension created by *newaxis* has a length of one. The newaxis approach is convenient for generating the proper dimensioned arrays for vector and matrix mathematics.

## NumPy Arrays are NOT immutable (sadly)

The copy function can be used to create a new, separate copy of an array in memory if needed

In [44]:
a = np.array([1, 2, 3], float)
b = a
c = a.copy()

print(a, b, c)

[ 1.  2.  3.] [ 1.  2.  3.] [ 1.  2.  3.]


In [45]:
a[0] = 0

print(a, b, c)

[ 0.  2.  3.] [ 0.  2.  3.] [ 1.  2.  3.]


In [46]:
#http://stackoverflow.com/questions/5541324/immutable-numpy-array
#http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flags.html
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

## Other Useful functions/properties

* **dtype**: property tells you what type of values are stored by the array
* **len()**: function returns the length of the first axis
* **in**: statement can be used to test if values are present in an array
* **tolist()**: create lists from Arrays
* **fill()**: fill an Array with a single value
* **transpose()**: create a new array with the final two axes switched
* **flatten()**: generate one-dimensional versions of multi-dimensional arrays 
* **concatenate()**: concatenate two or more arrays (provided as a tuple)
    - If an array has more than one dimension, we can specify the axis along which multiple arrays are concatenated
    - By default it concatenates along the first dimension

In [49]:
a.dtype

dtype('int64')

In [50]:
len(a)

10

In [52]:
2 in a

True

In [53]:
-1 in a

False

In [55]:
a.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
a = np.array([1, 2, 3], float)
a.fill(0)
a

array([ 0.,  0.,  0.])

In [59]:
a = np.array(range(6), float).reshape((2, 3))
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [60]:
a.transpose()

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

In [61]:
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [63]:
a.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.])

In [64]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)

np.concatenate((a, b, c))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [65]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

np.concatenate((a,b))

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [66]:
np.concatenate((a,b), axis=0)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [67]:
np.concatenate((a,b), axis=1)

array([[ 1.,  2.,  5.,  6.],
       [ 3.,  4.,  7.,  8.]])

# 2 - Array Mathematics

* When standard mathematical operations are used with arrays, they are applied on an elementby-element basis
* This means that the arrays should be the same size during addition, subtraction, etc

In [96]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

print("  a: ", a)
print("  b: ", b)
print("a+b: ", a + b)
print("a-b: ", a - b)
print("a*b: ", a * b)
print("a/b: ", a / b)
print("a%b: ", a % b)
print("a^b: ", a ** b)

  a:  [ 1.  2.  3.]
  b:  [ 5.  2.  6.]
a+b:  [ 6.  4.  9.]
a-b:  [-4.  0. -3.]
a*b:  [  5.   4.  18.]
a/b:  [ 0.2  1.   0.5]
a%b:  [ 1.  0.  3.]
a^b:  [   1.    4.  729.]


In [97]:
a = np.array([1,2,3,4], float)
b = np.array([5,2,6], float)

a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Unlike R, the smaller operand is not recycled

For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication

In [98]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)

a * b

array([[  2.,   0.],
       [  3.,  12.]])

* Errors are thrown if arrays do not match in size (as we already saw)
* However, arrays that do not match in the number of dimensions will be broadcasted by Python to perform mathematical operations
* This often means that the smaller array will be repeated as necessary to perform the operation indicated

In [5]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

print("a:\n", a)
print("b:\n", b)
print("a+b:\n", a + b)

a:
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
b:
 [-1.  3.]
a+b:
 [[ 0.  5.]
 [ 2.  7.]
 [ 4.  9.]]


In [6]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], int)

print("a:\n", a)
print("b:\n", b)
print("a+b:\n", a + b)

a:
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
b:
 [-1  3]
a+b:
 [[ 0.  5.]
 [ 2.  7.]
 [ 4.  9.]]


Here, the one-dimensional array b was broadcasted to a two-dimensional array that matched the size of a. In essence, b was repeated for each item in a, as if it were given by

    array([[-1., 3.],
     [-1., 3.],
     [-1., 3.]])

* Python automatically broadcasts arrays in this manner
* Sometimes, however, how we should broadcast is ambiguous
* In these cases, we can use the newaxis constant to specify how we want to broadcast

In [103]:
a = np.zeros((2,2), float)
b = np.array([-1., 3.], float)

print("a:\n", a)
print("b:\n", b)
print("a+b:\n", a + b)

print("a + b[np.newaxis,:]\n", a + b[np.newaxis,:])
print("a + b[:,np.newaxis]\n", a + b[:,np.newaxis])

a:
 [[ 0.  0.]
 [ 0.  0.]]
b:
 [-1.  3.]
a+b:
 [[-1.  3.]
 [-1.  3.]]
a + b[np.newaxis,:]
 [[-1.  3.]
 [-1.  3.]]
a + b[:,np.newaxis]
 [[-1. -1.]
 [ 3.  3.]]


Other useful functions:

* sqrt (np.sqrt(a))
* floor
* ceil
* rint (nearest rounded integer)
* abs
* sign
* log
* log10
* exp
* pi (np.pi)
* e (np.e)

# Array Iteration

Similar to Lists

In [105]:
a = np.array([1, 4, 5], int)
for x in a:
    print(x)

1
4
5


For multidimensional arrays, iteration proceeds over the first axis such that each loop returns a subsection of the array

In [107]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]


Multiple assignment can also be used with array iteration

In [109]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for (x, y) in a:
    print(x * y)

2.0
12.0
30.0


# Convenient Array Functions

In [117]:
a = np.array([2, 2, 4, 3], float)

For most of the routines described below, both standalone and member functions are available

In [118]:
a.sum()

9.0

In [119]:
np.sum(a)

9.0

In [121]:
a.prod()

24.0

In [112]:
np.prod(a)

24.0

In [113]:
a.mean()

3.0

In [114]:
np.mean(a)

3.0

In [116]:
a.var()

0.66666666666666663

In [115]:
np.var(a)

0.66666666666666663

In [122]:
a.std()

0.81649658092772603

In [123]:
np.std(a)

0.81649658092772603

In [124]:
a.min()

2.0

In [128]:
a.max()

4.0

The argmin and argmax functions return the array indices of the minimum and maximum values

In [7]:
a.argmin()

0

In [8]:
a[a.argmin()]

array([ 1.,  2.])

In [127]:
a.argmax()

1

For multidimensional arrays, each of the functions thus far described can take an optional argument axis that will perform an operation along only the specified axis, placing the results in a return array

In [129]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)

print("a:\n", a)
print("a.mean():\n", a.mean())
print("a.mean(axis=0):\n", a.mean(axis=0))
print("a.mean(axis=1):\n", a.mean(axis=1))

a:
 [[ 0.  2.]
 [ 3. -1.]
 [ 3.  5.]]
a.mean():
 2.0
a.mean(axis=0):
 [ 2.  2.]
a.mean(axis=1):
 [ 1.  1.  4.]


Like lists, arrays can be sorted

In [134]:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [135]:
a

array([ 6.,  2.,  5., -1.,  0.])

In [132]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

Notice that the member function changed the data structure itself.

Values in an array can be "clipped" to be within a prespecified range. This is the same as applying

    min(max(x, minval), maxval)
    
to each element x in an array

In [136]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)
a

array([ 6.,  2.,  5., -1.,  0.])

Unique elements can be extracted from an array

In [137]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([ 1.,  4.,  5.,  7.])

the diagonal can be extracted

In [138]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([ 1.,  4.])

# Comparing Arrays

* Boolean comparisons can be used to compare members elementwise on arrays of equal size.
* The return value is an array of Boolean True / False values

In [142]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)

c = a > b
c

array([ True, False, False], dtype=bool)

In [140]:
a == b

array([False,  True, False], dtype=bool)

In [141]:
a <= b

array([False,  True,  True], dtype=bool)

Arrays can be compared to single values using *broadcasting*

In [143]:
a = np.array([1, 3, 0], float)
a > 2

array([False,  True, False], dtype=bool)

The *any* and *all* operators can be used to determine whether or not any or all elements of a Boolean array are true

In [144]:
c = np.array([ True, False, False], bool)
any(c)

True

In [145]:
all(c)

False

Compound Boolean expressions can be applied to arrays on an element-by-element basis using special functions
* logical_and()
* logical_or()
* logical_not()

In [146]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False], dtype=bool)

In [147]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False], dtype=bool)

In [148]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True], dtype=bool)

* The where function forms a new array from two arrays of equivalent size using a Boolean filter to choose between elements of the two. 
* Its basic syntax is

      where(boolarray, truearray, falsearray)
* Similar to ifelse in R

In [149]:
a = np.array([1, 3, 0], float)
np.where(a != 0, 1 / a, a)

/Users/soumendra/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in true_divide
  from ipykernel import kernelapp as app


array([ 1.        ,  0.33333333,  0.        ])

Broadcasting can also be used with the where function

In [150]:
 np.where(a > 0, 3, 2)

array([3, 3, 2])

* A number of functions allow testing of the values in an array
* The *nonzero* function gives a tuple of indices of the nonzero values in an array
* The number of items in the tuple equals the number of axes of the array

In [151]:
a = np.array([[0, 1], [3, 0]], float)
a.nonzero()

(array([0, 1]), array([1, 0]))

In [156]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([  1.,  nan,  inf])

In [157]:
np.isnan(a)

array([False,  True, False], dtype=bool)

In [158]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

# Array Selectors

Earlier we saw Array subsetting functions similar to those available for Lists. Now let's take a look at more such functions which don't have a counter-part for Lists

## Subset by Boolean values

In [159]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]], dtype=bool)

In [161]:
a[a >= 6]

array([ 6.,  9.])

In [162]:
a[np.logical_and(a > 5, a < 9)]

array([ 6.])

## Subset by Integer Arrays/Lists

In [163]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In other words, we take the 0th, 0th, 1st, 3rd, 2nd, and 1st elements of a, in that order, when we use b to select elements from a

In [164]:
a = np.array([2, 4, 6, 8], float)
a[[0, 0, 1, 3, 2, 1]]

array([ 2.,  2.,  4.,  8.,  6.,  4.])

For multidimensional arrays, we have to send multiple one-dimensional integer arrays to the selection bracket, one for each axis. Then, each of these selection arrays is traversed in sequence: the first element taken has a first axis index taken from the first member of the first selection array, a second index from the first member of the second selection array, and so on

In [165]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)

a[b,c]

array([  1.,   4.,  16.,  16.,   4.])

*take()* is identical to bracket selection

In [10]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)

a.take(b)

array([ 2.,  2.,  4.,  8.,  6.,  4.])

take also provides an axis argument, such that subsections of an multi-dimensional array can be taken across a given dimension

In [167]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0, 0, 1], int)

a.take(b, axis=0)

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 2.,  3.]])

In [168]:
a.take(b, axis=1)

array([[ 0.,  0.,  1.],
       [ 2.,  2.,  3.]])

The opposite of the take function is the put function, which will take values from a source array and place them at specified indices in the array calling put

In [169]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)

a.put([0, 3], b)
a

array([ 9.,  1.,  2.,  8.,  4.,  5.])

* Note that the value 7 from the source array b is not used, since only two indices [0, 3] are specified.
* The source array will be repeated as necessary if not the same size.

# Vector Mathematics

Dot product

In [171]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

In [173]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)

np.dot(b, a)

array([  6.,  11.])

In [174]:
np.dot(a, b)

array([  3.,  13.])

In [175]:
np.dot(a, c)

array([[  4.,   0.],
       [ 14.,   2.]])

In [176]:
np.dot(c, a)

array([[ 2.,  4.],
       [ 0.,  4.]])

* NumPy also comes with a number of built-in routines for linear algebra calculations
* These can be found in the sub-module linalg
    - determinant (det())
    - inverse (inv())

In [177]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
np.linalg.det(a)

-48.000000000000028

In [178]:
np.linalg.inv(a)

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [180]:
np.dot(a, np.linalg.inv(a))

array([[  1.00000000e+00,   0.00000000e+00,  -2.22044605e-16],
       [  0.00000000e+00,   1.00000000e+00,  -2.77555756e-17],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

Eigen values and Eigen vector

In [182]:
vals, vecs = np.linalg.eig(a)
print("vals:\n", vals)
print("vecs:\n", vecs)

vals:
 [ 8.85591316  1.9391628  -2.79507597]
vecs:
 [[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


Singular value decomposition

In [183]:
a = np.array([[1, 3, 4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a)

print("U:\n", U)
print("s:\n", s)
print("Vh:\n", Vh)

U:
 [[-0.6113829  -0.79133492]
 [-0.79133492  0.6113829 ]]
s:
 [ 7.46791327  2.86884495]
Vh:
 [[-0.61169129 -0.45753324 -0.64536587]
 [ 0.78971838 -0.40129005 -0.46401635]
 [-0.046676   -0.79349205  0.60678804]]


# Statistics

The correlation coefficient for multiple variables observed at multiple instances can be found for arrays of the form [[x1, x2, …], [y1, y2, …], [z1, z2, …], …] where x, y, z are different observables and the numbers indicate the attribute

In [184]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
c

array([[ 1.        ,  0.72870505],
       [ 0.72870505,  1.        ]])

Here the return array c[i,j] gives the correlation coefficient for the ith and jth observables. Similarly, the covariance for data can be found

In [185]:
np.cov(a)

array([[ 0.91666667,  2.08333333],
       [ 2.08333333,  8.91666667]])

## Random Seeds

* NumPy's built-in pseudorandom number generator routines are in the sub-module *random*.
* The numbers are pseudo random in the sense that they are generated deterministically from a seed number, but are distributed in what has statistical similarities to random fashion.
* NumPy uses a particular algorithm called the Mersenne Twister to generate pseudorandom numbers
* Always use random seeds to make your simulations reproducible or if you want to debug
* Any program that starts with the same seed will generate exactly the same sequence of random numbers each time it is run

In [187]:
np.random.seed(293423)

In [190]:
np.random.rand(5)   #from half-open interval [0.0, 1.0)

array([ 0.82198398,  0.90239653,  0.8385685 ,  0.02638565,  0.33681448])

In [192]:
np.random.rand(2,3)

array([[ 0.45719255,  0.60260853,  0.2006835 ],
       [ 0.90558592,  0.35803445,  0.7351465 ]])

In [193]:
np.random.random() #generate a single random number

0.5100350802938722

To generate random integers in the range [min, max) use *randint(min, max)*

In [194]:
np.random.randint(5, 10)

9

In each of these examples, we drew random numbers form a uniform distribution. NumPy also includes generators for many other distributions.

In [195]:
 np.random.poisson(6.0)   #lambda

6

In [196]:
np.random.normal(1.5, 4.0)   #Gaussian, mu, sigma

-0.6521589481033394

In [197]:
np.random.normal()   #Gaussian, standard normal

-0.6046396572175571

In [198]:
 np.random.normal(size=5)   #multiple

array([ 0.56725291, -0.68585071,  0.28749073, -1.52034522, -1.05312974])

The random module can also be used to randomly shuffle an array (by default along the first dimension).

In [206]:
np.random.shuffle(a)
a

array([[ 5.,  3.,  1.,  8.],
       [ 1.,  2.,  1.,  3.]])

Notice that the shuffle function modifies the list in place, meaning it does not return a new list
but rather modifies the original list itself.